#!/usr/bin/env bash
set -Eeuo pipefail

# Preinstall / bootstrap script for Kontext MCP stack.
# Idempotent: safe to rerun. Creates docker network, .env, builds images, prefetches model.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "[kontext-preinstall] Starting bootstrap in $REPO_ROOT"

if ! command -v docker >/dev/null 2>&1; then
  echo "[kontext-preinstall] ERROR: docker not found in PATH" >&2
  exit 1
fi

# Ensure external reverse-proxy network exists (Caddy, etc.).
NET_NAME="appsnet"
if ! docker network inspect "$NET_NAME" >/dev/null 2>&1; then
  echo "[kontext-preinstall] Creating docker network $NET_NAME"
  docker network create "$NET_NAME"
else
  echo "[kontext-preinstall] Network $NET_NAME already exists"
fi

# Generate .env if missing.
if [[ ! -f .env ]]; then
  echo "[kontext-preinstall] Creating .env"
  # Strong random 32 byte secret (base64 stripped '=' chars)
  if command -v openssl >/dev/null 2>&1; then
    SESSION_SECRET="$(openssl rand -base64 32 | tr -d '=\n')"
  else
    SESSION_SECRET="$(head -c 48 /dev/urandom | base64 | tr -d '=\n')"
  fi
  cat > .env <<EOF
# Auto-generated by scripts/preinstall.sh
DB_NAME=mcp_db
DB_USER=mcp_user
DB_PASSWORD=mcp_password
EMBEDDING_MODEL_PATH=BAAI/bge-large-en-v1.5
EMBEDDING_QUANTIZED=true
CRAWLER_MODE=daemon
CRAWLER_PORT=8080
CRAWLER_AUTH_USERNAME=admin
# bcrypt for "changeme" (change before production!)
CRAWLER_AUTH_PASSWORD_BCRYPT=\$2a\$12\$zgLQbn7GZlf1qnUxQuFQ8OzM.NMBvvXVbh3S7gi934P1OxNmVP9xW
CRAWLER_SESSION_SECRET=${SESSION_SECRET}
LOG_LEVEL=INFO
CRAWLER_INDEXER_BASE_URL=http://mcp-server:8081
EOF
else
  echo "[kontext-preinstall] .env already present; leaving intact"
fi

echo "[kontext-preinstall] Building images (may take several minutes first time)"
docker compose build --progress=plain

echo "[kontext-preinstall] Standing up postgres to allow model prefetch"
docker compose up -d postgres
echo "[kontext-preinstall] Waiting for postgres health (timeout 60s)"
for i in {1..60}; do
  state=$(docker inspect --format '{{.State.Health.Status}}' mcp-postgres || echo 'missing')
  [[ "$state" == "healthy" ]] && break
  sleep 1
done
if [[ "$state" != "healthy" ]]; then
  echo "[kontext-preinstall] WARNING: postgres not healthy after 60s (state=$state)"
fi

echo "[kontext-preinstall] Starting mcp-server & crawler (model download warm-up)"
docker compose up -d mcp-server crawler

echo "[kontext-preinstall] Tailing initial crawler log for model download status (10s)"
timeout 10s docker logs -f mcp-crawler || true

# Determine project name (defaults to directory name) for volume lookup
PROJECT_NAME=$(basename "$PWD" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-_')
VOLUME_NAME="${PROJECT_NAME}_model_cache"

echo "[kontext-preinstall] Current model cache contents (volume: $VOLUME_NAME):" 
docker run --rm -v "${VOLUME_NAME}:/app/models" alpine:3.20 /bin/sh -c 'ls -1 /app/models || true'

echo "[kontext-preinstall] Done. To restart Caddy with new routes: ../restart-caddy.sh"
echo "[kontext-preinstall] Access dashboard via https://dash.kontext.staticvar.dev (or /dashboard path on kontext.staticvar.dev)."